/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tanvi
 */

import java.sql.*;
import java.util.ArrayList;
import surveysystem.ConnectionProvider;
import javax.swing.JOptionPane;

public class Participate extends javax.swing.JFrame {

    /**
     * Creates new form Participate
     */
    
    Connection con;
    Statement stmt;
    private static String userid;
    private static String surveyid;
    private static String survey_name;
    private static int num_questions;
    private static String curr_ques_id;
    static ArrayList<ArrayList<String>> questions;
    static ArrayList<ArrayList<String>> answers;
    
    public Participate() {
        initComponents();
    }
    
    public Participate(String user) {
        initComponents();
        try{
            con = ConnectionProvider.getConnection();
            stmt = con.createStatement();
        }catch(Exception e){
            e.printStackTrace();
            System.out.println(e);
            JOptionPane.showMessageDialog(null,"Could not start the application!");
        }
        
        userid = user;
        
        surveyid = null;
        survey_name = null;
        num_questions = 0;
        curr_ques_id = null;
        questions = new ArrayList<>();
        answers = new ArrayList<>();  
        
        jButton2.setEnabled(false);
        
        jLabel4.setText("");
        jLabel5.setText("");
        jRadioButton1.setText("");
        jRadioButton2.setText("");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Participate");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 240, 40));

        jButton9.setBackground(new java.awt.Color(255, 153, 153));
        jButton9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(102, 102, 102));
        jButton9.setText("X");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 40, -1));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Question :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 111, 28));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 109, 283, -1));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Survey Id :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 111, 28));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("this is the question");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 173, 430, 28));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Option 1");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 219, 100, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Option 2");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 249, 100, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Option 3");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 279, 100, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Option 4");
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 309, 100, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 111, -1));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 102));
        jLabel5.setText("qno / outof");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 111, 28));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg_dashboard.jpg"))); // NOI18N
        jLabel6.setBorder(null);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 630, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void getNextQuestion(){
        System.out.println(questions);
        buttonGroup1.clearSelection();
        ArrayList<String> row = questions.get(questions.size() - num_questions);
        // System.out.println(row);
        curr_ques_id = row.get(5);
        jLabel4.setText(row.get(0));
        jRadioButton1.setText(row.get(1));
        jRadioButton2.setText(row.get(2));
        jRadioButton3.setText(row.get(3));
        jRadioButton4.setText(row.get(4));
        
        jRadioButton1.setActionCommand("1" + row.get(1));
        jRadioButton2.setActionCommand("2" + row.get(2));
        jRadioButton3.setActionCommand("3" + row.get(3));
        jRadioButton4.setActionCommand("4" + row.get(4));
        num_questions--;
        jLabel5.setText(Integer.toString(questions.size() - num_questions) + "/" + Integer.toString(questions.size()));
    }
    
    void submitQuestion()
    {
        ArrayList<String> thisAns = new ArrayList<>();
        String ans = buttonGroup1.getSelection().getActionCommand();
        //System.out.println(buttonGroup1.getSelection());
        thisAns.add(curr_ques_id);        
        thisAns.add(ans.substring(0,1));
        thisAns.add(ans.substring(1,ans.length()));
        answers.add(thisAns);
    }
    
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here: Close
        setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: start
        String id = jTextField1.getText();
        if(id.length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Cannot be blank!");            
        }else{
            String query = "SELECT survey_id,survey_name,num_questions FROM survey_details WHERE survey_id = "+id+" AND created_by != "+userid+";";
            try{
                ResultSet rs1 = stmt.executeQuery(query);
                if(rs1.next())
                {
                    surveyid = id;
                    num_questions = rs1.getInt("num_questions");
                    survey_name = rs1.getString("survey_name");
                    jLabel1.setText(survey_name);
                    String query2 = "SELECT * FROM questions WHERE survey_id = "+id+";";
                    try{
                        ResultSet rs = stmt.executeQuery(query2);
                        while(rs.next())
                        {
                            ArrayList<String> q = new ArrayList<>();
                            q.add(rs.getString("question"));
                            q.add(rs.getString("opt1"));
                            q.add(rs.getString("opt2"));
                            q.add(rs.getString("opt3"));
                            q.add(rs.getString("opt4"));
                            q.add(Integer.toString(rs.getInt("id"))); // check
                            questions.add(q);
                            //q.clear();
                        }
                        jButton1.setEnabled(false);
                        jButton2.setEnabled(true);
                        rs.close();
                    }catch(Exception e2)
                    {
                        e2.printStackTrace();
                        System.out.println(e2);
                        setVisible(false);
                        JOptionPane.showMessageDialog(null, "Error!Could not fetch questions:");
                    }
                    
                    getNextQuestion();
                }else{
                    System.out.println("Not available! Please re-enter id:");
                    JOptionPane.showMessageDialog(null, "Not available! Please re-enter id:");
                }
                
                rs1.close();
            }catch(Exception e)
            {
                e.printStackTrace();
                System.out.println(e);
                JOptionPane.showMessageDialog(null, e);
                setVisible(false);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: next / submit
        if(num_questions == 0){
            // submit
            submitQuestion();
            String query1= "INSERT INTO log(userid,surveyid) VALUES("+userid+","+surveyid+");";
            String query2 = "UPDATE survey_details SET num_participants  = num_participants  + 1 WHERE survey_id = "+surveyid+";";
            try{
                stmt.executeUpdate(query1);
                stmt.executeUpdate(query2);
                for(ArrayList<String> ans : answers)
                {
                    String query3 = "INSERT INTO log_questions VALUES("+userid+","+ans.get(0)+","+ans.get(1)+",'"+ans.get(2)+"');";
                    String query4 = "UPDATE questions SET cnt"+ans.get(1)+" = cnt"+ans.get(1)+" + 1 WHERE id = "+ans.get(0)+";";
                    try{
                        stmt.executeUpdate(query3);
                        stmt.executeUpdate(query4);
                    }catch(Exception eb)
                    {
                        eb.printStackTrace();
                        System.out.println(eb);
                        JOptionPane.showMessageDialog(null, eb);
                        setVisible(false);
                    }
                }
                JOptionPane.showMessageDialog(null, "Completed Survey Succesfully! Thankyou!");
                setVisible(false);
            }catch(Exception ea)
            {
                ea.printStackTrace();
                System.out.println(ea);
                JOptionPane.showMessageDialog(null, ea);
                setVisible(false);
            }

        }else{
            submitQuestion();
            getNextQuestion();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Participate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Participate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Participate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Participate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Participate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
